apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
destination:
  name: 'argocd'
  namespace: default
  server: 'https://kubernetes.default.svc'
source:
  path: namespaces-config
  repoURL: 'https://github.com/Navid284/blog-example-repo.git'
  targetRevision: HEAD
project: default