apiVersion: v1
kind: Namespace
metadata:
  name: namespace-team1
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
